name: laras_mobile
description: Laras self-hosted and local music player.
publish_to: "none"
version: 0.9.0+4

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  just_audio: ^0.9.42
  audio_session: ^0.1.25
  audio_service: ^0.18.15
  just_audio_background: ^0.0.1-beta.13
  on_audio_query: ^2.9.0
  permission_handler: ^11.3.1
  file_picker: ^8.1.4
  shared_preferences: ^2.3.3
  path_provider: ^2.1.5
  sqflite: ^2.4.3
  audio_metadata_reader: ^1.6.0
  flutter_bloc: ^8.1.6
  equatable: ^2.0.7
  intl: ^0.20.2
  home_widget: ^0.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

dependency_overrides:
  just_audio_background:
    path: third_party/just_audio_background

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
    - android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_dark.png
    - android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_neon.png
    - android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png
    - android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground_dark.png
    - android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground_neon.png
